#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     arm2,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     arm1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     left,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "macro.h/record.h"
#include "JoystickDriver.c"

const int CONTROLLER_THRESHOLD = 10;

//variables
int x1, x2, y1, y2;

task main()
{

	startRecording(3, 0, 6, 0, "macro1.txt");

	//receive input
	while(recording) //this is where driver-controlled period code goes
  {
    getJoystickSettings(joystick);

    //controls
    x1 = joystick.joy1_x1;
    x2 = joystick.joy1_x2;
    y1 = joystick.joy1_y1;
    y2 = joystick.joy1_y2;
    if (abs(x1) < CONTROLLER_THRESHOLD) {
    	x1 = 0;
    }
   	if (abs(x2) < CONTROLLER_THRESHOLD) {
   		x2 = 0;
   	}
   	if (abs(y1) < CONTROLLER_THRESHOLD) {
   		y1 = 0;
   	}
   	if (abs(y2) < CONTROLLER_THRESHOLD) {
   		y2 = 0;
   	}

   	//logic and stuff
   	motor[left] = y1;
   	motor[right] = y2;

   	if (joy1Btn(5)) {
   		motor[arm1] = 50;
   	} else if (joy1Btn(6)) {
   		motor[arm1] = -50;
   	} else {
   		motor[arm1] = 0;
   	}

   	//stop program
   	if (joy1Btn(9)) {
   		recording = false;
   	}

   	update();
  }

	stopRecording();

}
